var annotated_dup =
[
    [ "audio", "namespaceaudio.html", [
      [ "Listener", "structaudio_1_1Listener.html", "structaudio_1_1Listener" ],
      [ "ListenerImpl", "structaudio_1_1ListenerImpl.html", "structaudio_1_1ListenerImpl" ],
      [ "Speaker", "structaudio_1_1Speaker.html", "structaudio_1_1Speaker" ],
      [ "SpeakerImpl", "structaudio_1_1SpeakerImpl.html", "structaudio_1_1SpeakerImpl" ],
      [ "Track", "structaudio_1_1Track.html", "structaudio_1_1Track" ],
      [ "TrackImpl", "structaudio_1_1TrackImpl.html", "structaudio_1_1TrackImpl" ]
    ] ],
    [ "gfx", "namespacegfx.html", [
      [ "PendingBufferBarrier", "structgfx_1_1PendingBufferBarrier.html", "structgfx_1_1PendingBufferBarrier" ],
      [ "PendingImageBarrier", "structgfx_1_1PendingImageBarrier.html", "structgfx_1_1PendingImageBarrier" ],
      [ "vl", "structgfx_1_1vl.html", "structgfx_1_1vl" ],
      [ "vlBuffer", "structgfx_1_1vlBuffer.html", "structgfx_1_1vlBuffer" ],
      [ "vlBufferImpl", "structgfx_1_1vlBufferImpl.html", "structgfx_1_1vlBufferImpl" ],
      [ "vlBufferState", "structgfx_1_1vlBufferState.html", "structgfx_1_1vlBufferState" ],
      [ "vlBufferUtil", "structgfx_1_1vlBufferUtil.html", "structgfx_1_1vlBufferUtil" ],
      [ "vlCommandBuffer", "structgfx_1_1vlCommandBuffer.html", "structgfx_1_1vlCommandBuffer" ],
      [ "vlCommandBufferCreateInfo", "structgfx_1_1vlCommandBufferCreateInfo.html", "structgfx_1_1vlCommandBufferCreateInfo" ],
      [ "vlCommandBufferImpl", "structgfx_1_1vlCommandBufferImpl.html", "structgfx_1_1vlCommandBufferImpl" ],
      [ "vlCommandPool", "structgfx_1_1vlCommandPool.html", "structgfx_1_1vlCommandPool" ],
      [ "vlCommandPoolImpl", "structgfx_1_1vlCommandPoolImpl.html", "structgfx_1_1vlCommandPoolImpl" ],
      [ "vlCreateInfo", "structgfx_1_1vlCreateInfo.html", "structgfx_1_1vlCreateInfo" ],
      [ "vlDescriptorSetLayout", "structgfx_1_1vlDescriptorSetLayout.html", "structgfx_1_1vlDescriptorSetLayout" ],
      [ "vlDescriptorSetLayoutBinding", "structgfx_1_1vlDescriptorSetLayoutBinding.html", "structgfx_1_1vlDescriptorSetLayoutBinding" ],
      [ "vlDescriptorSetLayoutImpl", "structgfx_1_1vlDescriptorSetLayoutImpl.html", "structgfx_1_1vlDescriptorSetLayoutImpl" ],
      [ "vlDescriptorSetLayoutSource", "structgfx_1_1vlDescriptorSetLayoutSource.html", "structgfx_1_1vlDescriptorSetLayoutSource" ],
      [ "vlDeviceMemory", "structgfx_1_1vlDeviceMemory.html", "structgfx_1_1vlDeviceMemory" ],
      [ "vlDeviceMemoryCreateInfo", "structgfx_1_1vlDeviceMemoryCreateInfo.html", "structgfx_1_1vlDeviceMemoryCreateInfo" ],
      [ "vlDeviceMemoryImpl", "structgfx_1_1vlDeviceMemoryImpl.html", "structgfx_1_1vlDeviceMemoryImpl" ],
      [ "vlDynamicBuffer", "structgfx_1_1vlDynamicBuffer.html", "structgfx_1_1vlDynamicBuffer" ],
      [ "vlFence", "structgfx_1_1vlFence.html", "structgfx_1_1vlFence" ],
      [ "vlFenceImpl", "structgfx_1_1vlFenceImpl.html", "structgfx_1_1vlFenceImpl" ],
      [ "vlFrameBuffer", "structgfx_1_1vlFrameBuffer.html", "structgfx_1_1vlFrameBuffer" ],
      [ "vlFrameBufferCreateInfo", "structgfx_1_1vlFrameBufferCreateInfo.html", "structgfx_1_1vlFrameBufferCreateInfo" ],
      [ "vlFrameBufferImpl", "structgfx_1_1vlFrameBufferImpl.html", "structgfx_1_1vlFrameBufferImpl" ],
      [ "vlFrameChain", "structgfx_1_1vlFrameChain.html", "structgfx_1_1vlFrameChain" ],
      [ "vlFrameChainCreateInfo", "structgfx_1_1vlFrameChainCreateInfo.html", "structgfx_1_1vlFrameChainCreateInfo" ],
      [ "vlFrameChainImpl", "structgfx_1_1vlFrameChainImpl.html", "structgfx_1_1vlFrameChainImpl" ],
      [ "vlImage", "structgfx_1_1vlImage.html", "structgfx_1_1vlImage" ],
      [ "vlImageState", "structgfx_1_1vlImageState.html", "structgfx_1_1vlImageState" ],
      [ "vlImageView", "structgfx_1_1vlImageView.html", "structgfx_1_1vlImageView" ],
      [ "vlImageViewImpl", "structgfx_1_1vlImageViewImpl.html", "structgfx_1_1vlImageViewImpl" ],
      [ "vlImpl", "structgfx_1_1vlImpl.html", "structgfx_1_1vlImpl" ],
      [ "vlPipeline", "structgfx_1_1vlPipeline.html", "structgfx_1_1vlPipeline" ],
      [ "vlPipelineBuilder", "structgfx_1_1vlPipelineBuilder.html", "structgfx_1_1vlPipelineBuilder" ],
      [ "vlPipelineImpl", "structgfx_1_1vlPipelineImpl.html", "structgfx_1_1vlPipelineImpl" ],
      [ "vlPipelineLayout", "structgfx_1_1vlPipelineLayout.html", "structgfx_1_1vlPipelineLayout" ],
      [ "vlPipelineLayoutImpl", "structgfx_1_1vlPipelineLayoutImpl.html", "structgfx_1_1vlPipelineLayoutImpl" ],
      [ "vlPipelineSet", "structgfx_1_1vlPipelineSet.html", "structgfx_1_1vlPipelineSet" ],
      [ "vlQueue", "structgfx_1_1vlQueue.html", "structgfx_1_1vlQueue" ],
      [ "vlQueueImpl", "structgfx_1_1vlQueueImpl.html", "structgfx_1_1vlQueueImpl" ],
      [ "vlQueuePresentInfo", "structgfx_1_1vlQueuePresentInfo.html", "structgfx_1_1vlQueuePresentInfo" ],
      [ "vlQueueSubmissionResult", "structgfx_1_1vlQueueSubmissionResult.html", "structgfx_1_1vlQueueSubmissionResult" ],
      [ "vlQueueSubmitInfo", "structgfx_1_1vlQueueSubmitInfo.html", "structgfx_1_1vlQueueSubmitInfo" ],
      [ "vlQueueWait", "structgfx_1_1vlQueueWait.html", "structgfx_1_1vlQueueWait" ],
      [ "vlRenderContext", "structgfx_1_1vlRenderContext.html", "structgfx_1_1vlRenderContext" ],
      [ "vlRenderPass", "structgfx_1_1vlRenderPass.html", "structgfx_1_1vlRenderPass" ],
      [ "vlRenderPassCreateInfo", "structgfx_1_1vlRenderPassCreateInfo.html", "structgfx_1_1vlRenderPassCreateInfo" ],
      [ "vlRenderPassImpl", "structgfx_1_1vlRenderPassImpl.html", "structgfx_1_1vlRenderPassImpl" ],
      [ "vlSemaphore", "structgfx_1_1vlSemaphore.html", "structgfx_1_1vlSemaphore" ],
      [ "vlSemaphoreImpl", "structgfx_1_1vlSemaphoreImpl.html", "structgfx_1_1vlSemaphoreImpl" ],
      [ "vlShaderModule", "structgfx_1_1vlShaderModule.html", "structgfx_1_1vlShaderModule" ],
      [ "vlShaderModuleImpl", "structgfx_1_1vlShaderModuleImpl.html", "structgfx_1_1vlShaderModuleImpl" ],
      [ "vlSubRenderPassCreateInfo", "structgfx_1_1vlSubRenderPassCreateInfo.html", "structgfx_1_1vlSubRenderPassCreateInfo" ],
      [ "vlSurface", "structgfx_1_1vlSurface.html", "structgfx_1_1vlSurface" ],
      [ "vlSurfaceImpl", "structgfx_1_1vlSurfaceImpl.html", "structgfx_1_1vlSurfaceImpl" ],
      [ "vlSwapChain", "structgfx_1_1vlSwapChain.html", "structgfx_1_1vlSwapChain" ],
      [ "vlSwapChainImpl", "structgfx_1_1vlSwapChainImpl.html", "structgfx_1_1vlSwapChainImpl" ],
      [ "vlTransitionMode", "structgfx_1_1vlTransitionMode.html", "structgfx_1_1vlTransitionMode" ],
      [ "vlVertex", "structgfx_1_1vlVertex.html", "structgfx_1_1vlVertex" ],
      [ "vlWait", "structgfx_1_1vlWait.html", "structgfx_1_1vlWait" ],
      [ "vlWindow", "structgfx_1_1vlWindow.html", "structgfx_1_1vlWindow" ],
      [ "vlWindowCreateInfo", "structgfx_1_1vlWindowCreateInfo.html", "structgfx_1_1vlWindowCreateInfo" ],
      [ "vlWindowImpl", "structgfx_1_1vlWindowImpl.html", "structgfx_1_1vlWindowImpl" ]
    ] ],
    [ "io", "namespaceio.html", [
      [ "DataSource", "structio_1_1DataSource.html", "structio_1_1DataSource" ],
      [ "Driver", "structio_1_1Driver.html", "structio_1_1Driver" ],
      [ "DriverCreateInfo", "structio_1_1DriverCreateInfo.html", "structio_1_1DriverCreateInfo" ],
      [ "File", "structio_1_1File.html", "structio_1_1File" ],
      [ "FileContent", "structio_1_1FileContent.html", "structio_1_1FileContent" ],
      [ "FileImpl", "structio_1_1FileImpl.html", "structio_1_1FileImpl" ],
      [ "LinuxDriver", "structio_1_1LinuxDriver.html", "structio_1_1LinuxDriver" ]
    ] ],
    [ "ntl", "namespacentl.html", [
      [ "slab", "classntl_1_1slab.html", "classntl_1_1slab" ],
      [ "slotter", "classntl_1_1slotter.html", "classntl_1_1slotter" ]
    ] ],
    [ "serialize", "namespaceserialize.html", [
      [ "TrackData", "structserialize_1_1TrackData.html", "structserialize_1_1TrackData" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< ptr_set< T > >", "structstd_1_1hash_3_01ptr__set_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01ptr__set_3_01T_01_4_01_4" ],
      [ "hash< SharedSetKey< T > >", "structstd_1_1hash_3_01SharedSetKey_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01SharedSetKey_3_01T_01_4_01_4" ],
      [ "hash< std::vector< T > >", "structstd_1_1hash_3_01std_1_1vector_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1vector_3_01T_01_4_01_4" ]
    ] ],
    [ "vm", "namespacevm.html", [
      [ "AsEngineImpl", "structvm_1_1AsEngineImpl.html", "structvm_1_1AsEngineImpl" ],
      [ "AsModuleImpl", "structvm_1_1AsModuleImpl.html", "structvm_1_1AsModuleImpl" ],
      [ "Engine", "structvm_1_1Engine.html", "structvm_1_1Engine" ],
      [ "ExecutionParameter", "structvm_1_1ExecutionParameter.html", "structvm_1_1ExecutionParameter" ],
      [ "ExecutionResult", "structvm_1_1ExecutionResult.html", null ],
      [ "Module", "structvm_1_1Module.html", "structvm_1_1Module" ],
      [ "ModuleBuilder", "structvm_1_1ModuleBuilder.html", "structvm_1_1ModuleBuilder" ],
      [ "SymbolTable", "structvm_1_1SymbolTable.html", "structvm_1_1SymbolTable" ]
    ] ],
    [ "Allocator", "structAllocator.html", "structAllocator" ],
    [ "AllocatorChecker", "classAllocatorChecker.html", "classAllocatorChecker" ],
    [ "Application", "structApplication.html", "structApplication" ],
    [ "ASYNC", "structASYNC.html", "structASYNC" ],
    [ "AudioTest", "structAudioTest.html", "structAudioTest" ],
    [ "cache", "structcache.html", "structcache" ],
    [ "CopyOperation", "structCopyOperation.html", "structCopyOperation" ],
    [ "CopySchedule", "structCopySchedule.html", "structCopySchedule" ],
    [ "dim3", "structdim3.html", "structdim3" ],
    [ "drmp3", "structdrmp3.html", "structdrmp3" ],
    [ "drmp3_allocation_callbacks", "structdrmp3__allocation__callbacks.html", "structdrmp3__allocation__callbacks" ],
    [ "drmp3_config", "structdrmp3__config.html", "structdrmp3__config" ],
    [ "drmp3_metadata", "structdrmp3__metadata.html", "structdrmp3__metadata" ],
    [ "drmp3_seek_point", "structdrmp3__seek__point.html", "structdrmp3__seek__point" ],
    [ "drmp3dec", "structdrmp3dec.html", "structdrmp3dec" ],
    [ "drmp3dec_frame_info", "structdrmp3dec__frame__info.html", "structdrmp3dec__frame__info" ],
    [ "drwav", "structdrwav.html", "structdrwav" ],
    [ "drwav__memory_stream", "structdrwav____memory__stream.html", "structdrwav____memory__stream" ],
    [ "drwav__memory_stream_write", "structdrwav____memory__stream__write.html", "structdrwav____memory__stream__write" ],
    [ "drwav_data_format", "structdrwav__data__format.html", "structdrwav__data__format" ],
    [ "drwav_fmt", "structdrwav__fmt.html", "structdrwav__fmt" ],
    [ "ExecutionContext", "structExecutionContext.html", "structExecutionContext" ],
    [ "FOR", "structFOR.html", "structFOR" ],
    [ "IApplication", "structIApplication.html", "structIApplication" ],
    [ "Loader", "structLoader.html", "structLoader" ],
    [ "monitor", "classmonitor.html", "classmonitor" ],
    [ "monitor_lock", "structmonitor__lock.html", "structmonitor__lock" ],
    [ "Object", "structObject.html", "structObject" ],
    [ "OpStats", "structOpStats.html", "structOpStats" ],
    [ "ptr", "structptr.html", "structptr" ],
    [ "ptr_common", "structptr__common.html", "structptr__common" ],
    [ "ptr_object", "structptr__object.html", "structptr__object" ],
    [ "ptr_set", "structptr__set.html", "structptr__set" ],
    [ "raw", "structraw.html", "structraw" ],
    [ "shared_monitor", "classshared__monitor.html", "classshared__monitor" ],
    [ "SharedSetKey", "structSharedSetKey.html", "structSharedSetKey" ],
    [ "signal", "structsignal.html", "structsignal" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "stbrp_context", "structstbrp__context.html", "structstbrp__context" ],
    [ "stbrp_node", "structstbrp__node.html", "structstbrp__node" ],
    [ "stbrp_rect", "structstbrp__rect.html", "structstbrp__rect" ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", "structstbtt____bitmap" ],
    [ "stbtt__buf", "structstbtt____buf.html", "structstbtt____buf" ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", "structstbtt__aligned__quad" ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", "structstbtt__bakedchar" ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", "structstbtt__fontinfo" ],
    [ "stbtt_kerningentry", "structstbtt__kerningentry.html", "structstbtt__kerningentry" ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", "structstbtt__pack__context" ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", "structstbtt__pack__range" ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", "structstbtt__packedchar" ],
    [ "stbtt_vertex", "structstbtt__vertex.html", "structstbtt__vertex" ],
    [ "threadpool", "classthreadpool.html", "classthreadpool" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "TimerRegion", "structTimerRegion.html", "structTimerRegion" ],
    [ "Vertex", "structVertex.html", "structVertex" ],
    [ "Waitable", "structWaitable.html", "structWaitable" ],
    [ "WaitList", "structWaitList.html", "structWaitList" ],
    [ "WaitVector", "structWaitVector.html", "structWaitVector" ]
];